### ISSUE TITLE
spec-cleaner destorys gcc-c++ BuildRequires

### ISSUE THREAD

**Issue by jubalh** [openSUSE/spec-cleaner#112] opened 2016-04-19 10:16 UTC
Running `spec-cleaner -i myfile.spec` in version 0.8.0 results in:
```
-BuildRequires:  gcc-c++
+BuildRequires:  +
+BuildRequires:  -
+BuildRequires:  c
+BuildRequires:  g
```

**Comment by scarabeusiv** [comment] 2016-04-19 10:17
Duplicate of issue #108

**Closed by scarabeusiv** 2016-04-19 10:17 UTC
