### ISSUE TITLE
Disable {}ing transformation by default

### ISSUE THREAD

**Issue by jengelh** [openSUSE/spec-cleaner#54] opened 2015-03-14 11:39 UTC
spec-cleaner-0.6.8 modifies nearly *everything* of a specfile, including:
```
-%define         libsoname %name-2_0-5
+%define         libsoname %{name}-2_0-5
```
This change is controversial at best and should not be done implicitly, that is to say, whether or not the output uses %foo throughout or %{foo} throughout ought to become a command-line option.

**Comment by sleep-walker** [comment] 2015-03-14 18:40
This is feature, not bug. Intention for this is to unify the look to make the review easier.

**Comment by jengelh** [comment] 2015-03-14 18:51
As if. This "feature" causes one thing: diff noise. Especially when the entire specfile is already using %foo everywhere, it makes review HARDER.

**Comment by sleep-walker** [comment] 2015-03-14 20:24
As some people prefer %foo over %{foo}, it is expected that unification will lead to diff noise ONCE. I'm afraid that it is inevitable consequence of unification. Unification is good, unification is way to go!

Even though I know that your name from openSUSE project for quite some time, I don't remember you being reviewer. spec-cleaner did great job already on improving quality of spec files. Do we really need to have this conversation where your only argument was emotional?

**Comment by jengelh** [comment] 2015-03-14 21:25
Everybody who receives an SR - that includes package maintainers - is a reviewer so to speak.
I do not see the quality of packages improved by cluttering them with {}.
You overrate unification, but for what it is worth, I am totally on the unification track: People generally don't do {} for variables in shell scripts, Perl, PHP etc., so it is only consequent that I do not do it for rpmspecs either.

**Comment by scarabeusiv** [comment] 2015-03-16 10:11
The "curlification" as I call it is most fuzz causing thing the spec-cleaner does (also one with most test-cases in the testsuite).

Anyway the logic is as this:
If it is variable it should be %{variable}
If it is command/macro it should be %command

You as maintainer should not bother wether you yourself bracket or not as the spec-cleaner should do it correctly for you anyway.

From the techincal issues what does %versiona mean? is it %{version}a or %{versiona} so the strict not bracketing is not working, and for semantic the above was created testcased and proven quite rock-solid for usage.

As you justify your non-curlifying the language to compare is probably bash, it is always safer to use var=${var1}...

FWIW with the complex reviews, there is always good way how to do it:
1) run technical changes and submit it
2) run spec-cleaner over it and submit again
This sadly caused some trouble with reviewers, because nobody wanted to review just-spec-cleaner changes as they on their own do not pose so much extra benefit.
Also the review is harder only for first run, later runs are producing exactly same output so this is moot for further updates of already spec-cleaned package.

If you find any curlification bugs please report them here in batch or individualy (there might be macros I am not aware of (ie I didn't try this thing on mono packages ever), but so far it should not cause any regressions or trouble for the spec-file.

This is not a bug but personal opinion. Thus closing.

**Closed by scarabeusiv** 2015-03-16 10:11 UTC
